name: CI

on:
  push:
    branches: "**"
    pull_request:
    tags:
      - "**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.8"
    - run: swift --version
    - uses: actions/checkout@v3
    - run: swift test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=sha,format=long
          type=semver,pattern={{version}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
